# Generated by Django 4.2.9 on 2024-02-20 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options_post_lead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='lead',
            new_name='excert',
        ),
    ]
