# Generated by Django 4.2.9 on 2024-02-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avatar',
            field=models.ImageField(default='/blog/avatar/default.jpg', upload_to='blog/avatar'),
        ),
    ]
