# Generated by Django 5.0.2 on 2024-03-02 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
